// Generated by gencpp from file python_turtle/addturtle.msg
// DO NOT EDIT!


#ifndef PYTHON_TURTLE_MESSAGE_ADDTURTLE_H
#define PYTHON_TURTLE_MESSAGE_ADDTURTLE_H

#include <ros/service_traits.h>


#include <python_turtle/addturtleRequest.h>
#include <python_turtle/addturtleResponse.h>


namespace python_turtle
{

struct addturtle
{

typedef addturtleRequest Request;
typedef addturtleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addturtle
} // namespace python_turtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::python_turtle::addturtle > {
  static const char* value()
  {
    return "77308e5f6594808d16ab77e3e54c717b";
  }

  static const char* value(const ::python_turtle::addturtle&) { return value(); }
};

template<>
struct DataType< ::python_turtle::addturtle > {
  static const char* value()
  {
    return "python_turtle/addturtle";
  }

  static const char* value(const ::python_turtle::addturtle&) { return value(); }
};


// service_traits::MD5Sum< ::python_turtle::addturtleRequest> should match 
// service_traits::MD5Sum< ::python_turtle::addturtle > 
template<>
struct MD5Sum< ::python_turtle::addturtleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::python_turtle::addturtle >::value();
  }
  static const char* value(const ::python_turtle::addturtleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_turtle::addturtleRequest> should match 
// service_traits::DataType< ::python_turtle::addturtle > 
template<>
struct DataType< ::python_turtle::addturtleRequest>
{
  static const char* value()
  {
    return DataType< ::python_turtle::addturtle >::value();
  }
  static const char* value(const ::python_turtle::addturtleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::python_turtle::addturtleResponse> should match 
// service_traits::MD5Sum< ::python_turtle::addturtle > 
template<>
struct MD5Sum< ::python_turtle::addturtleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::python_turtle::addturtle >::value();
  }
  static const char* value(const ::python_turtle::addturtleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_turtle::addturtleResponse> should match 
// service_traits::DataType< ::python_turtle::addturtle > 
template<>
struct DataType< ::python_turtle::addturtleResponse>
{
  static const char* value()
  {
    return DataType< ::python_turtle::addturtle >::value();
  }
  static const char* value(const ::python_turtle::addturtleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PYTHON_TURTLE_MESSAGE_ADDTURTLE_H
