// Generated by gencpp from file python_turtle/removeturtleRequest.msg
// DO NOT EDIT!


#ifndef PYTHON_TURTLE_MESSAGE_REMOVETURTLEREQUEST_H
#define PYTHON_TURTLE_MESSAGE_REMOVETURTLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace python_turtle
{
template <class ContainerAllocator>
struct removeturtleRequest_
{
  typedef removeturtleRequest_<ContainerAllocator> Type;

  removeturtleRequest_()
    : turtle_name()  {
    }
  removeturtleRequest_(const ContainerAllocator& _alloc)
    : turtle_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _turtle_name_type;
  _turtle_name_type turtle_name;





  typedef boost::shared_ptr< ::python_turtle::removeturtleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::python_turtle::removeturtleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct removeturtleRequest_

typedef ::python_turtle::removeturtleRequest_<std::allocator<void> > removeturtleRequest;

typedef boost::shared_ptr< ::python_turtle::removeturtleRequest > removeturtleRequestPtr;
typedef boost::shared_ptr< ::python_turtle::removeturtleRequest const> removeturtleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::python_turtle::removeturtleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::python_turtle::removeturtleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace python_turtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'python_turtle': ['/home/iamnotedible/RR_turtle_example/ROS/src/python_turtle/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::python_turtle::removeturtleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_turtle::removeturtleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_turtle::removeturtleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48e762ec9b058c0b3f8e7717c102b90d";
  }

  static const char* value(const ::python_turtle::removeturtleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48e762ec9b058c0bULL;
  static const uint64_t static_value2 = 0x3f8e7717c102b90dULL;
};

template<class ContainerAllocator>
struct DataType< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "python_turtle/removeturtleRequest";
  }

  static const char* value(const ::python_turtle::removeturtleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string turtle_name\n"
;
  }

  static const char* value(const ::python_turtle::removeturtleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtle_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct removeturtleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::python_turtle::removeturtleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::python_turtle::removeturtleRequest_<ContainerAllocator>& v)
  {
    s << indent << "turtle_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.turtle_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYTHON_TURTLE_MESSAGE_REMOVETURTLEREQUEST_H
