// Generated by gencpp from file python_turtle/setcolor.msg
// DO NOT EDIT!


#ifndef PYTHON_TURTLE_MESSAGE_SETCOLOR_H
#define PYTHON_TURTLE_MESSAGE_SETCOLOR_H

#include <ros/service_traits.h>


#include <python_turtle/setcolorRequest.h>
#include <python_turtle/setcolorResponse.h>


namespace python_turtle
{

struct setcolor
{

typedef setcolorRequest Request;
typedef setcolorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setcolor
} // namespace python_turtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::python_turtle::setcolor > {
  static const char* value()
  {
    return "4e5c5e738507cfbcc1070c9c1e8f412e";
  }

  static const char* value(const ::python_turtle::setcolor&) { return value(); }
};

template<>
struct DataType< ::python_turtle::setcolor > {
  static const char* value()
  {
    return "python_turtle/setcolor";
  }

  static const char* value(const ::python_turtle::setcolor&) { return value(); }
};


// service_traits::MD5Sum< ::python_turtle::setcolorRequest> should match 
// service_traits::MD5Sum< ::python_turtle::setcolor > 
template<>
struct MD5Sum< ::python_turtle::setcolorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::python_turtle::setcolor >::value();
  }
  static const char* value(const ::python_turtle::setcolorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_turtle::setcolorRequest> should match 
// service_traits::DataType< ::python_turtle::setcolor > 
template<>
struct DataType< ::python_turtle::setcolorRequest>
{
  static const char* value()
  {
    return DataType< ::python_turtle::setcolor >::value();
  }
  static const char* value(const ::python_turtle::setcolorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::python_turtle::setcolorResponse> should match 
// service_traits::MD5Sum< ::python_turtle::setcolor > 
template<>
struct MD5Sum< ::python_turtle::setcolorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::python_turtle::setcolor >::value();
  }
  static const char* value(const ::python_turtle::setcolorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_turtle::setcolorResponse> should match 
// service_traits::DataType< ::python_turtle::setcolor > 
template<>
struct DataType< ::python_turtle::setcolorResponse>
{
  static const char* value()
  {
    return DataType< ::python_turtle::setcolor >::value();
  }
  static const char* value(const ::python_turtle::setcolorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PYTHON_TURTLE_MESSAGE_SETCOLOR_H
