// Generated by gencpp from file python_turtle/setpose.msg
// DO NOT EDIT!


#ifndef PYTHON_TURTLE_MESSAGE_SETPOSE_H
#define PYTHON_TURTLE_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <python_turtle/setposeRequest.h>
#include <python_turtle/setposeResponse.h>


namespace python_turtle
{

struct setpose
{

typedef setposeRequest Request;
typedef setposeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setpose
} // namespace python_turtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::python_turtle::setpose > {
  static const char* value()
  {
    return "c7286894f126aa93e3ce655b0b322988";
  }

  static const char* value(const ::python_turtle::setpose&) { return value(); }
};

template<>
struct DataType< ::python_turtle::setpose > {
  static const char* value()
  {
    return "python_turtle/setpose";
  }

  static const char* value(const ::python_turtle::setpose&) { return value(); }
};


// service_traits::MD5Sum< ::python_turtle::setposeRequest> should match 
// service_traits::MD5Sum< ::python_turtle::setpose > 
template<>
struct MD5Sum< ::python_turtle::setposeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::python_turtle::setpose >::value();
  }
  static const char* value(const ::python_turtle::setposeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_turtle::setposeRequest> should match 
// service_traits::DataType< ::python_turtle::setpose > 
template<>
struct DataType< ::python_turtle::setposeRequest>
{
  static const char* value()
  {
    return DataType< ::python_turtle::setpose >::value();
  }
  static const char* value(const ::python_turtle::setposeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::python_turtle::setposeResponse> should match 
// service_traits::MD5Sum< ::python_turtle::setpose > 
template<>
struct MD5Sum< ::python_turtle::setposeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::python_turtle::setpose >::value();
  }
  static const char* value(const ::python_turtle::setposeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::python_turtle::setposeResponse> should match 
// service_traits::DataType< ::python_turtle::setpose > 
template<>
struct DataType< ::python_turtle::setposeResponse>
{
  static const char* value()
  {
    return DataType< ::python_turtle::setpose >::value();
  }
  static const char* value(const ::python_turtle::setposeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PYTHON_TURTLE_MESSAGE_SETPOSE_H
