// Generated by gencpp from file python_turtle/setposeResponse.msg
// DO NOT EDIT!


#ifndef PYTHON_TURTLE_MESSAGE_SETPOSERESPONSE_H
#define PYTHON_TURTLE_MESSAGE_SETPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace python_turtle
{
template <class ContainerAllocator>
struct setposeResponse_
{
  typedef setposeResponse_<ContainerAllocator> Type;

  setposeResponse_()
    : ret(0)  {
    }
  setposeResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
  (void)_alloc;
    }



   typedef int8_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::python_turtle::setposeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::python_turtle::setposeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setposeResponse_

typedef ::python_turtle::setposeResponse_<std::allocator<void> > setposeResponse;

typedef boost::shared_ptr< ::python_turtle::setposeResponse > setposeResponsePtr;
typedef boost::shared_ptr< ::python_turtle::setposeResponse const> setposeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::python_turtle::setposeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::python_turtle::setposeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace python_turtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'python_turtle': ['/home/iamnotedible/Desktop/RR_turtle_reverse/ROS/src/python_turtle/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::python_turtle::setposeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::python_turtle::setposeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_turtle::setposeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_turtle::setposeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_turtle::setposeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_turtle::setposeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::python_turtle::setposeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba0ef05866f4fc5d7e82544d27e5cfbc";
  }

  static const char* value(const ::python_turtle::setposeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba0ef05866f4fc5dULL;
  static const uint64_t static_value2 = 0x7e82544d27e5cfbcULL;
};

template<class ContainerAllocator>
struct DataType< ::python_turtle::setposeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "python_turtle/setposeResponse";
  }

  static const char* value(const ::python_turtle::setposeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::python_turtle::setposeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ret\n"
"\n"
;
  }

  static const char* value(const ::python_turtle::setposeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::python_turtle::setposeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setposeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::python_turtle::setposeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::python_turtle::setposeResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYTHON_TURTLE_MESSAGE_SETPOSERESPONSE_H
