// Generated by gencpp from file python_turtle/setposeRequest.msg
// DO NOT EDIT!


#ifndef PYTHON_TURTLE_MESSAGE_SETPOSEREQUEST_H
#define PYTHON_TURTLE_MESSAGE_SETPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace python_turtle
{
template <class ContainerAllocator>
struct setposeRequest_
{
  typedef setposeRequest_<ContainerAllocator> Type;

  setposeRequest_()
    : turtle_pose()  {
    }
  setposeRequest_(const ContainerAllocator& _alloc)
    : turtle_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _turtle_pose_type;
  _turtle_pose_type turtle_pose;





  typedef boost::shared_ptr< ::python_turtle::setposeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::python_turtle::setposeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setposeRequest_

typedef ::python_turtle::setposeRequest_<std::allocator<void> > setposeRequest;

typedef boost::shared_ptr< ::python_turtle::setposeRequest > setposeRequestPtr;
typedef boost::shared_ptr< ::python_turtle::setposeRequest const> setposeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::python_turtle::setposeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::python_turtle::setposeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace python_turtle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'python_turtle': ['/home/iamnotedible/RR_turtle_example/ROS/src/python_turtle/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::python_turtle::setposeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::python_turtle::setposeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_turtle::setposeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::python_turtle::setposeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_turtle::setposeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::python_turtle::setposeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::python_turtle::setposeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91edf5f7b15029459831b436799cd78a";
  }

  static const char* value(const ::python_turtle::setposeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91edf5f7b1502945ULL;
  static const uint64_t static_value2 = 0x9831b436799cd78aULL;
};

template<class ContainerAllocator>
struct DataType< ::python_turtle::setposeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "python_turtle/setposeRequest";
  }

  static const char* value(const ::python_turtle::setposeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::python_turtle::setposeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped turtle_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::python_turtle::setposeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::python_turtle::setposeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtle_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setposeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::python_turtle::setposeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::python_turtle::setposeRequest_<ContainerAllocator>& v)
  {
    s << indent << "turtle_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.turtle_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PYTHON_TURTLE_MESSAGE_SETPOSEREQUEST_H
