(cl:defpackage python_turtle-srv
  (:use )
  (:export
   "ADDTURTLE"
   "<ADDTURTLE-REQUEST>"
   "ADDTURTLE-REQUEST"
   "<ADDTURTLE-RESPONSE>"
   "ADDTURTLE-RESPONSE"
   "REMOVETURTLE"
   "<REMOVETURTLE-REQUEST>"
   "REMOVETURTLE-REQUEST"
   "<REMOVETURTLE-RESPONSE>"
   "REMOVETURTLE-RESPONSE"
   "SETCOLOR"
   "<SETCOLOR-REQUEST>"
   "SETCOLOR-REQUEST"
   "<SETCOLOR-RESPONSE>"
   "SETCOLOR-RESPONSE"
   "SETPOSE"
   "<SETPOSE-REQUEST>"
   "SETPOSE-REQUEST"
   "<SETPOSE-RESPONSE>"
   "SETPOSE-RESPONSE"
  ))

